baseurl: "https://ematth.dev"
languageCode: "en-us"
title: "Evan Matthews"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: "ematth"
favicon: true

permalinks:
  note: "/note/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Updates
      url: "post/"
      weight: 5
    - name: Personal Blog
      url: "note/"
      weight: 6
    # - name: Sample Song Library
    #   url: "ssl/"
    #   weight: 6
    - name: Resume
      url: "resume/resume.pdf"
      weight: 3
    - name: CV
      url: "cv/cv.pdf"
      weight: 4
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    # - name: Tags
    #   url: "tags/"
    #   weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "Website created with Hugo and the XMin theme"
  footer: "&copy; Evan Matthews {Year} | [Github](https://github.com/evanmm3) | [LinkedIn](https://www.linkedin.com/in/ematth/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
